name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main # Ändra till den branch du vill deploya från

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specificera din Node.js-version

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run format

      - name: ESLint
        run: npm run lint

      # - name: Run tests
      #   run: npm test

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ci # Se till att bygget är klart innan deployment

    steps:
      - name: Check out repository content
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }} # Använd miljövariabeln

